<p>Terms and Conditions of booking</p>

<p>1.1 User Obligations<br/>You agree to be bound by the following obligations, including without limitation:<br/>a. you accept financial responsibility for all transactions made under any name or account; b. you must be 18 years of age or over and have legal capacity; c. you declare that you understand these Terms and Conditions; d. you warrant that all information you provide about yourself or anyone else shall be true and accurate; e. the Site must not be used for speculative, false or fraudulent bookings; f. any content the Site may not be modified, copied, transmitted, distributed, sold, displayed, licensed or reproduced in any way by you, except that one copy of the information contained within the Site may be made for your personal, non-commercial use. If you do so, you may not modify the content in any way.</p>
<p>1.2 Prices<br/>All prices stated on the Site are expressed in US Dollars and include service and VAT.</p>
<p>1.3 Booking procedure<br/>Upon completion of the reservation according to the instructions on the Site, you confirm the dates indicated on the booking form, as well as the number of rooms, the number of persons the chosen hotel and your acceptance of the conditions and contracted price of the reservation. The contracted price including any additional tax will be charged in full thirty (30) days prior to your arrival day to the credit card provided during the booking process. If we are not able to receive the reservation payment in full, thirty (30) days prior to your arrival, you will have a 24 hour grace period to complete the payment. If the full payment is not received within that grace period we reserve the right to cancel your booking and apply appropriate cancelation fees in accordance with section 1.7 For bookings made thirty (30) days or less prior to arrival date, the full amount corresponding to your reservation will be charged in full at the time of the booking to the credit card provided during the booking process.</p>
<p>1.4 Guarantee<br/>Each booking must be guaranteed with a credit card number. Please note the maximum number of reservations guaranteed under the same credit card is five (5). The credit card data will also be used to offset costs if you do not comply with the cancellation conditions on cancellation.</p>
<p>1.5 Special Requests<br/>Any special requests must be advised to us at the time of booking e.g. diet, room location, a particular facility at a hotel etc. Whilst every effort will be made by us to try and arrange your reasonable special requests, we cannot guarantee that they will be fulfilled. Any failure to meet special requests will not be a breach of contract on our part.</p>
<p>1.6 Changes by user<br/>If you wish to change any part of your booking after our confirmation invoice has been issued, you must inform us by means of filling in a form on the Site as soon as possible. This should be done by the person who made the booking. Whilst we will do our best to assist we cannot guarantee that we will be able to meet your requested change. Where we can meet a request, all changes will be subject to any applicable rate changes or extra costs incurred. Where we are unable to assist you and you do not wish to proceed with the original booking we will treat this as a cancellation by you. A cancellation fee may be payable in accordance with section 1.7.</p>
<p>1.7 Cancellation by user<br/>Cancellation of your booking must be made by means of filling in a form on the Site. Once the booking is cancelled, you receive a confirmation by e-mail which contains a cancellation number. This cancellation number acts as proof of your cancellation in the event of a dispute. For cancellations of bookings received 7 days or more prior to arrival, no cancellation fee is due. Cancellations of bookings received within 7 to 5 days prior to arrival will result in a cancellation fee equivalent to an average two nights stay from the booked period. Cancellations of bookings received within 4 days or less prior to arrival will result in a cancellation fee equivalent to the full amount due for the entire booked stay. Please be aware that no refunds will be issued for any unused portion of your stay. Our cancellation policies are applicable at all times without exception.</p>
<p>1.8 Changes or cancellation by Excellence Resorts We reserve the right to make changes or cancellations after the booking at any time, although we will endeavor not to make a major change or cancel the booking within 72 hours of the arrival date, except by reason of force majeure. If we have to make a major change to your arrangements after booking we will offer you the option of accepting the change or canceling the booking and receiving a full refund of any monies you may already have paid. We do not accept responsibility for any expenses or costs you may incur as a result of any change.</p>
<p>1.9 Incorrect Information<br/>Whilst every effort is made to ensure the accuracy of all information and prices displayed on this Site, regrettably errors do occasionally occur. In the event that an incorrect price has been entered in error, any booking made based on such incorrect price will not be valid. You will be advised of the mistake at the earliest opportunity and you will then have the option either to pay the correct price for the hotel arrangements or to cancel and receive a full refund of any monies you may already have paid.</p>
<p>1.10 Fees<br/>We may charge a fee for the service provided when you book accommodations through the Site. Any such service fee is non- refundable. In addition, you will be responsible for all charges, fees, duties, taxes and assessment arising out of your use of the services available on the Site.</p>
<p>1.11 Force Majeure<br/>We do not accept liability or pay compensation for any loss, damage or expense where the performance of our service is prevented or affected by reason of force majeure. Force Majeure means any event which we could not, even with all due care, foresee or avoid such as war or threat of war, riots, civil strife, terrorist activity, industrial action, natural or nuclear disaster, fire, adverse weather conditions, closure of airports or ports, technical problems with transport, governmental action and all other similar events.</p>
<p>1.12 Guest behavior<br/>In the event of a termination of your hotel arrangement by the hotel (manager) by reason of improper conduct, our liability to you and /or your party will cease. We will have no further obligations to you and/ or your party. No refunds for lost accommodation or any other service will be made and we will not pay any expenses or costs incurred as a result of the termination.</p>
<p>2. Change of Terms and Conditions<br/>We reserve the right to change these Terms and Conditions as well as the contents of this Site, including the availability of any suppliers, features, information, database or content, for any reason and without notice, and without liability to you, any other user or third party. This right shall not affect the Terms and Conditions accepted by you upon making a legitimate reservation using this website. You should check these Terms and Conditions for any changes each time you access the Site.</p>
<p>3. Indemnification<br/>You agree to indemnify Excellence Resorts and each of their respective officers, directors, employees ad agents from and against any claim, cause of action or demand, including without limitation reasonable legal and accounting fees in any action filed or commenced by any third party against Excellence Resorts as a result of (i) your breach of these Terms and Conditions or the documents made part of these Terms and Conditions by reference, (ii) your violation of any law or the rights of a third party or (iii) your use of our Site.</p>
<p>4. Jurisdiction<br/>Access to this Site is conditional upon your agreement that all information contained in it and all matters which arise between you and Excellence Resorts will be governed by Dutch law. Access is further conditional upon your agreement that any dispute or matter which arises between you and Excellence Resorts will be dealt with exclusively by the courts of the Netherlands. If any part of these Terms and Conditions is unlawful, void, or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of any remaining provisions. Possible evidence of use of this Site for illegal purposes will be provided to law enforcement authorities.</p>
<p>5. Contact Information<br/>If you have any questions or concerns about these Terms or if you need further assistance with respect to access to or use of the Site or the services offered by Excellence Resorts, you may contact info@excellence-resorts.com as indicated below. We will attempt to respond to your questions or concerns promptly after we receive them.</p>
